layouts/default.vue

- Add secondary menu for account routes
Closes #41

feat: #41 add secondary account menu

---

pages/payment/index.vue

- Improve loading state of Payment page
Page title now appears with contents of the page. The content appears only after user payment details are loaded and check for payment details has been performed.
Closes #42

feat: #42 payment page improve loading

---

components/general/TitleAnchored/index.vue
pages/index.vue
pages/payment/index.vue
pages/payment/invoices.vue
pages/profile/address.vue
pages/profile/identity.vue

- Add anchored titles component and apply for all the titles
Close #50

feat: #50 add anchored titles

---

layouts/default.vue
pages/support.vue
plugins/app-routes.js

- Add "Support" in sidebar menu and corresponding page
- Add support message form with validation
Closes #57

feat: #57 add support page

---

components/sections/payment/PaymentMethodAdd/index.vue

- Add console log with strip card details when running locally
Closes #59

feat: #59 log card token in dev env

---

layouts/default.vue
services/aws/AWSClient.js
services/aws/CognitoSync.js
store/auth.js
store/payment.js
store/user.js

- Integrate CognitoSync
- Create logic to fetch and update user custom settings with minimized sidebar setting as an example
Closes #46

feat: #46 cognito sync integration and minimized sidebar user settings

---

layouts/default.vue

- Move account menu to dedicated toolbar button "Menu"
Closes #61

feat: #61 account menu add dedicated button

---

layouts/error.vue

- Add custom layout to display global errors in more user friendly way
Closes #64

feat: #64 add nicer error layout

---

pages/support.vue

- Add expectation field (required, min 10 words)
- Disable expectation field if issue field is not valid

feat: #79 support page extend fields

---

components/common/AColumn/index.vue
components/sections/payment/PaymentMethodAdd/index.vue
components/sections/payment/PaymentMethodDetails/index.vue
components/sections/profile/ProfileAddress/index.vue
components/sections/profile/ProfileDetails/index.vue
pages/help.vue
pages/index.vue
pages/profile/invoices.vue
pages/support.vue
plugins/app-components.js

- Add `AColumn` component that disables Vuetify column padding but keeps the rest of options
- Apply the component on all the pages

feat: #80 add a-column component and apply on every pages

---

components/sections/profile/ProfileDetails/index.vue
layouts/default.vue

- Align secondary navigation tabs with page content
Closes #86

feat: #86 align secondary nav tabs with content

---

config/loading.js
nuxt.config.js
templates/loading-indicator.html

- Added dark theme to app loading screen
- Changed spinner to match app loaders
Closes #89

feat: #89 customize loading screen to match app theme

---

layouts/default.vue

- Change footer links separator color to match top border
Closes #92

bug: #92 fix footer separator line color

---

pages/help.vue
pages/help/index.vue

- Separate help page with cards for list and article content
- Add rounded borders to articles list items
Closes #95

feat: #95 help separate page with cards

---

layouts/default.vue

- Remove logout button from toolbar
- Add logout button to sidebar above footer
Closes #96

feat: #96 reposition logout button

---

pages/debug.vue
plugins/app-routes.js

- Create debug page (`/debug`) and with user cognito ID displayed
Closes #91

feat: #91 create debug page

---

components/sections/profile/ProfileAddress/index.vue
components/sections/profile/ProfileDetails/index.vue
pages/profile/payment.vue

- Make notification messages unique
Closes #98

feat: #98 make snackbar messages unique

---

components/sections/profile/ProfileDetails/index.vue
store/user.js

- Remove last name field and validation
- Adjust form styling to keep cards height equal
Closes #106

feat: #106 identity remove last name

---

components/sections/profile/ProfileDetails/index.vue

- Change order of first name and email fields on identity page
Closes #135

feat: #135 identity change fields order

---

pages/profile/invoices/index.vue

- Add label to invoices table pagination
Closes #138

feat: #138 invoices add pagination label

---

pages/profile/invoices/_invoiceId.vue
pages/profile/invoices/index.vue

- Use small chip size for invoice paid status
Closes #141

feat: #141 invoice paid use small chips

---

pages/help.vue

- Help articles selection list add bottom margin to list items
Closes #142

feat: #142 help list add margins

---

components/general/AppToolbar/index.vue

- Add margin to the left of notification bell in app toolbar
Closes #144

feat: #144 add notification bell margin

---

components/general/AppToolbar/index.vue

- Add notifications list side padding
Closes #145

feat: #145 add notifications list padding

---

plugins/aws-amplify-setup.js
services/aws/AWSClient.js
services/aws/S3.js
store/user.js

- Remove Amplify Storage usage
- Integrate S3 client and apply for avatar requests
Closes #134

feat: #134 integrate aws s3

---

components/sections/support/SupportSteps/SupportStep1.vue
components/sections/support/SupportSteps/SupportStep2.vue
components/sections/support/SupportSteps/SupportStep3.vue
components/sections/support/SupportSteps/index.vue
pages/support.vue
plugins/vuelidate/validators.js

- Use stepper component for support page forms
Closes #143

feat: #143 support page use stepper

---

components/modals/ModalVerifyEmail/index.vue
components/sections/profile/ProfileDetails/index.vue
pages/auth.vue
store/auth.js

- Add user record update after successful email verification in email verification modal
- Add user record update on log in, in case authenticated user email does not match existing user record
Closes #163

feat: #163 update email in db after change

---

store/auth.js
store/invoices.js
store/payment.js

- Replace DDB table names with updated values
Closes #169

feat: #169 update ddb tables names

---

components/sections/support/SupportSteps/SupportStep1.vue
components/sections/support/SupportSteps/SupportStep2.vue
components/sections/support/SupportSteps/SupportStep3.vue
components/sections/support/SupportSteps/SupportStep4.vue
components/sections/support/SupportSteps/SupportStep5.vue
components/sections/support/SupportSteps/index.vue
pages/support.vue

- Make widget full width
- Add 2 more steps - loading, confirmation
- Rename Submit step to Preview
- Add back button where is necessary
Closes #171

feat: #171 support page improvements

---

store/auth.js
store/user.js

- Use AWS credentials identity id for storing & fetching user avatar
Closes #175

bug: #175 use aws credentials for avatar

---

components/sections/support/SupportSteps/index.vue
store/support.js

- Add ticket submission to S3 for support page
Note: currently not working. Added for debugging.
Closes #191

feat: #191 save support message to s3

---

store/auth.js
store/invoices.js
store/payment.js

@acidbiscuit please review this PR to make sure I did not brake anything.

#228 Updated the DDB queries

---

pages/profile/invoices/_invoiceId.vue

- Hide Download button on invoice details page if invoice is unpaid
Closes #219

feat: #219 invoice hide download when unpaid

---

pages/profile/invoices/_invoiceId.vue

- Add arbitrary 5 sec loading state when invoices download button is clicked
Closes #220

feat: #220 invoice download add loading

---

components/sections/support/SupportSteps/SupportStep2.vue
components/sections/support/SupportSteps/SupportStep3.vue

- Switch order of step buttons Next and Back
Closes #222

feat: #222 support change step actions order

---

pages/profile/invoices/_invoiceId.vue

- Do not display Amount field on invoice page if invoice is unpaid
Closes #226

feat: #226 invoice hide amount if unpaid

---

components/common/TitleAnchored/index.vue

- Increase anchored title animation speed x3
Closes #227

feat: #227 title anchored increase pulse interval

---

pages/profile/invoices/index.vue

- Add `N/A` placeholder for empty values on invoices page
Closes #224

feat: #224 invoices add empty values placeholder

---

components/sections/security/PasswordChange/index.vue
pages/profile/security.vue

- Adjust form card width on security page to occupy full card width
Closes #225

feat: #225 security adjust form card width

---

components/sections/support/SupportSteps/SupportStep4.vue

- Add "Loading" text under the spinner on Submitting step
Closes #223

feat: #223 support loading add text

---

components/general/AppToolbar/index.vue
components/sections/profile/ProfileDetails/index.vue

- Add grey color as avatar background
Closes #230

feat: #230 avatar add background color

---

components/general/AppToolbar/index.vue
layouts/default.vue
pages/profile/interface.vue
plugins/app-routes.js
services/aws/CognitoSync.js
store/user.js

- Add profile interface page
- Add Color Preference setting and store it in CognitoSync
- Set application theme from user color preference setting
Closes #214

feat: #214 add profile interface page

---

components/general/AppToolbar/index.vue

- Increase toolbar avatar size to previous measurements before changes #218 
Closes #248

feat: #248 avatar size reduce rollback #218

---

components/modals/ModalImageCrop/index.vue

- Add gray background to avatar preview in modal image crop
Closes #247

feat: #247 modal avatar add gray background

---

components/modals/ModalSubscription/index.vue
layouts/default.vue
pages/index.vue
plugins/app-routes.js
store/payment.js

- Add subscription modal and it's visibility management in the store
- Add "Save" button on home page to check user subscription
Closes #215

feat: #215 add subscription check action

---

pages/profile/invoices/index.vue
store/invoices.js

- Add pagination with total items count
Closes #178

feat: #178 invoices add pagination total

---

store/payment.js

I changed the SK to be the one that needs to be deleted.

New way to unsubscribe

---

templates/loading-indicator.html

- Increase loading indicator size
Closes #257

feat: #257 loading indicator increase size

---

components/general/AppToolbar/index.vue

- Separate logout menu item in the account menu in app toolbar
Closes #259

feat: #259 toolbar menu separate logout menu item

---

components/general/AppToolbar/index.vue

- Change Security tab and menu position in app toolbar
Closes #258

feat: #258 toolbar change security tab and menu order

---

layouts/default.vue

- Add larger paddings to layout container to match column gap
Closes #261

feat: #261 layout container increase side paddings

---

layouts/error.vue

- Change error layout links color to white
Closes #253

feat: #253 error layout links change color

---

pages/profile/invoices/index.vue

- Add year in title of invoices page
Closes #254

feat: #254 invoices add year in title

---

pages/profile/invoices/index.vue

- Add `N/A` for invoices next payment date column
Closes #256

feat: #256 invoices next payment add na

---

pages/profile/invoices/index.vue

- Change the way invoices pagination is displayed by showing previous and next years
Closes #255

feat: #255 invoices pagination change page nav

---

pages/auth.vue

- Change "Username" with "Email" on every used authentication screen
Closes #264

feat: #264 change auth username label with email

---

components/sections/payment/PaymentMethodAdd/index.vue

- Re-order subscription plan price and title
- Increase subscription plan price font size
- Improve mobile layout for subscription plan cards
Closes #262

feat: #262 reorder and increase subscription price cards titles

---

components/sections/payment/PaymentMethodAdd/index.vue

- Change coupon "Apply" text to "ChecK"
Closes #267

feat: #267 change coupon apply button text

---

components/sections/support/SupportSteps/index.vue

- Remove support page first step slide animation
Closes #289

feat: #289 support remove first step animation

---

components/general/AppToolbar/index.vue

- Move avatar to account menu as first item
Closes #293

feat: #293 move avatar to account menu
